name = "BARONTools"
uuid = "e94efa9a-e148-11e8-31d5-71956884d28d"
authors = ["Twan Koolen <koolen.twan@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
